apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-backend
  template:
    metadata:
      labels:
        app: movie-backend
    spec:
      containers:
      - name: backend
        image: YOUR_DOCKERHUB_USER/movie-backend:latest
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017/movieapp"
        ports:
        - containerPort: 5000
