apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: movie-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: your-domain.example
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: movie-frontend
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: movie-backend
            port:
              number: 5000
